import { MoodConfig } from "@/types/movie";

export const TMDB_BASE_URL = "https://api.themoviedb.org/3";
export const TMDB_IMAGE_BASE = "https://image.tmdb.org/t/p";

export const IMAGE_SIZES = {
  poster: {
    small: "w185",
    medium: "w342",
    large: "w500",
    xlarge: "w780",
  },
  backdrop: {
    small: "w300",
    medium: "w780",
    large: "w1280",
    original: "original",
  },
} as const;

export const MOODS: MoodConfig[] = [
  {
    id: "mind-bending",
    label: "Mind-Bending",
    subtitle: "Reality is a construct",
    genreIds: [878, 9648, 53],
    gradient: "from-violet-600/40 to-indigo-900/60",
    accentColor: "#7c3aed",
  },
  {
    id: "comfort",
    label: "Comfort",
    subtitle: "Warmth in every frame",
    genreIds: [35, 10751, 16],
    gradient: "from-amber-500/40 to-orange-900/60",
    accentColor: "#f59e0b",
  },
  {
    id: "dark",
    label: "Dark",
    subtitle: "Embrace the shadows",
    genreIds: [27, 53, 80],
    gradient: "from-red-900/40 to-zinc-900/60",
    accentColor: "#dc2626",
  },
  {
    id: "romantic",
    label: "Romantic",
    subtitle: "Stories of the heart",
    genreIds: [10749, 18],
    gradient: "from-pink-500/40 to-rose-900/60",
    accentColor: "#ec4899",
  },
  {
    id: "epic",
    label: "Epic",
    subtitle: "Legends never die",
    genreIds: [28, 12, 14],
    gradient: "from-cyan-500/40 to-blue-900/60",
    accentColor: "#06b6d4",
  },
  {
    id: "underrated",
    label: "Underrated",
    subtitle: "Hidden masterpieces await",
    genreIds: [18, 36, 10402],
    gradient: "from-emerald-500/40 to-teal-900/60",
    accentColor: "#10b981",
  },
];

export const ANIMATION = {
  ease: {
    hero: "expo.out",
    section: "power3.out",
    micro: "power2.out",
    bounce: "back.out(1.7)",
    /** Seamless idle drift — no discontinuity at loop boundaries */
    idle: "sine.inOut",
    /** Custom cubic-bezier for filter chips & micro-interactions */
    microCubic: [0.19, 1, 0.22, 1] as [number, number, number, number],
  },
  duration: {
    fast: 0.3,
    normal: 0.6,
    slow: 1.0,
    hero: 1.4,
    dramatic: 2.0,
    /** Hero entrance timeline total */
    heroEntrance: 1.6,
    /** Idle drift one-way (×2 for yoyo = 18s loop) */
    idleHalf: 9,
    /** Spin reveal poster scale-up */
    spinReveal: 0.9,
    /** ScrollTrigger scrub catch-up lag for cinematic feel */
    scrubLag: 1.2,
  },
  stagger: {
    fast: 0.03,
    normal: 0.06,
    slow: 0.1,
    /** Hero headline word stagger */
    heroWords: 0.08,
    /** Ghost poster entrance stagger */
    ghostPoster: 0.25,
  },
  /** Perspective & depth parameters */
  depth: {
    /** Root perspective on scene containers */
    perspective: 1200,
    /** translateZ range: min–max for poster depth mapping */
    zMin: 20,
    zMax: 260,
    /** Parallax translateY rates per layer (as % of scroll) */
    parallax: {
      background: -8,
      mid: -18,
      mid2: -28,
      foreground: -38,
    },
  },
} as const;

// Demo movie data for when no TMDB API key is available
export const DEMO_MOVIES = [
  {
    id: 550,
    title: "Fight Club",
    overview: "An insomniac office worker and a devil-may-care soap maker form an underground fight club.",
    poster_path: "/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    backdrop_path: "/hZkgoQYus5dXo3H8T7Uef6DNknx.jpg",
    release_date: "1999-10-15",
    vote_average: 8.4,
    vote_count: 26000,
    genre_ids: [18, 53],
    popularity: 73.5,
    original_language: "en",
    tagline: "Mischief. Mayhem. Soap.",
  },
  {
    id: 680,
    title: "Pulp Fiction",
    overview: "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales.",
    poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    backdrop_path: "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    release_date: "1994-09-10",
    vote_average: 8.5,
    vote_count: 25000,
    genre_ids: [53, 80],
    popularity: 70.2,
    original_language: "en",
    tagline: "Just because you are a character doesn't mean you have character.",
  },
  {
    id: 278,
    title: "The Shawshank Redemption",
    overview: "Imprisoned in the 1940s, banker Andy Dufresne begins to find ways to make his time less painful.",
    poster_path: "/9cjIGRiQocgamefsIRMERMkEfHD.jpg",
    backdrop_path: "/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
    release_date: "1994-09-23",
    vote_average: 8.7,
    vote_count: 24000,
    genre_ids: [18, 80],
    popularity: 82.1,
    original_language: "en",
    tagline: "Fear can hold you prisoner. Hope can set you free.",
  },
  {
    id: 13,
    title: "Forrest Gump",
    overview: "Forrest Gump, while not intelligent, has accidentally been present at many historic moments.",
    poster_path: "/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    backdrop_path: "/7c9UVPPiTPltouxRVY6N9uugaVA.jpg",
    release_date: "1994-06-23",
    vote_average: 8.5,
    vote_count: 25000,
    genre_ids: [35, 18, 10749],
    popularity: 65.3,
    original_language: "en",
    tagline: "The world will never be the same once you've seen it through the eyes of Forrest Gump.",
  },
  {
    id: 155,
    title: "The Dark Knight",
    overview: "Batman raises the stakes in his war on crime and faces the Joker, a criminal mastermind.",
    poster_path: "/qJ2tW6WMUDux911BTUgMIUraGe1.jpg",
    backdrop_path: "/nMKdUUepR0i5zn0y1T4CsSB5ez1.jpg",
    release_date: "2008-07-16",
    vote_average: 8.5,
    vote_count: 30000,
    genre_ids: [28, 80, 18],
    popularity: 90.0,
    original_language: "en",
    tagline: "Why so serious?",
  },
  {
    id: 27205,
    title: "Inception",
    overview: "A thief who steals corporate secrets through dream-sharing technology is given the task of planting an idea.",
    poster_path: "/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
    backdrop_path: "/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
    release_date: "2010-07-15",
    vote_average: 8.4,
    vote_count: 34000,
    genre_ids: [28, 878, 12],
    popularity: 95.3,
    original_language: "en",
    tagline: "Your mind is the scene of the crime.",
  },
  {
    id: 238,
    title: "The Godfather",
    overview: "Spanning the years 1945 to 1955, the story chronicles the Corleone family under patriarch Vito Corleone.",
    poster_path: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    backdrop_path: "/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
    release_date: "1972-03-14",
    vote_average: 8.7,
    vote_count: 18000,
    genre_ids: [18, 80],
    popularity: 85.7,
    original_language: "en",
    tagline: "An offer you can't refuse.",
  },
  {
    id: 569094,
    title: "Spider-Man: Across the Spider-Verse",
    overview: "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People.",
    poster_path: "/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    backdrop_path: "/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
    release_date: "2023-05-31",
    vote_average: 8.4,
    vote_count: 6000,
    genre_ids: [16, 28, 12],
    popularity: 130.5,
    original_language: "en",
    tagline: "It's how you wear the mask that matters.",
  },
  {
    id: 120,
    title: "The Lord of the Rings: The Fellowship of the Ring",
    overview: "Young hobbit Frodo Baggins must destroy the One Ring and end Sauron's reign of terror.",
    poster_path: "/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
    backdrop_path: "/pIUvQ9Ed35wlWhY2oU6OmwEgzx8.jpg",
    release_date: "2001-12-18",
    vote_average: 8.4,
    vote_count: 22000,
    genre_ids: [12, 14, 28],
    popularity: 75.2,
    original_language: "en",
    tagline: "One ring to rule them all.",
  },
  {
    id: 497,
    title: "The Green Mile",
    overview: "Guards on Death Row discover that a massive convict has a miraculous healing gift.",
    poster_path: "/velWPhVMQeQKcxggNEU8YmIo52R.jpg",
    backdrop_path: "/l6hQWH9eDksNJNiXWYRkWqikOdu.jpg",
    release_date: "1999-12-10",
    vote_average: 8.5,
    vote_count: 16000,
    genre_ids: [14, 18, 80],
    popularity: 60.5,
    original_language: "en",
    tagline: "Miracles do happen.",
  },
  {
    id: 603,
    title: "The Matrix",
    overview: "A computer hacker learns about the true nature of reality and his role in the war against its controllers.",
    poster_path: "/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    backdrop_path: "/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg",
    release_date: "1999-03-30",
    vote_average: 8.2,
    vote_count: 24000,
    genre_ids: [28, 878],
    popularity: 80.0,
    original_language: "en",
    tagline: "Welcome to the Real World.",
  },
  {
    id: 346,
    title: "Seven",
    overview: "Two detectives hunt a serial killer who uses the seven deadly sins as his motives.",
    poster_path: "/6yoghtyTpznpBik8EngEmJskVUO.jpg",
    backdrop_path: "/AfHknkSZ3MJbCIG3MWqMIf6VBqr.jpg",
    release_date: "1995-09-22",
    vote_average: 8.3,
    vote_count: 18000,
    genre_ids: [80, 9648, 53],
    popularity: 55.2,
    original_language: "en",
    tagline: "Seven deadly sins. Seven ways to die.",
  },
  {
    id: 807,
    title: "Se7en",
    overview: "Two homicide detectives are on a desperate hunt for a serial killer whose crimes are based on the seven deadly sins.",
    poster_path: "/69Sns8WoET6CfaYlIkHbla4l7nC.jpg",
    backdrop_path: "/AfHknkSZ3MJbCIG3MWqMIf6VBqr.jpg",
    release_date: "1995-09-22",
    vote_average: 8.3,
    vote_count: 12000,
    genre_ids: [80, 9648, 53],
    popularity: 50.2,
    original_language: "en",
    tagline: "Long is the way and hard that out of hell leads up to light.",
  },
  {
    id: 244786,
    title: "Whiplash",
    overview: "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing.",
    poster_path: "/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    backdrop_path: "/6ONB2oCa0W3ER7sUaEGaclC3Ijo.jpg",
    release_date: "2014-10-10",
    vote_average: 8.4,
    vote_count: 14000,
    genre_ids: [18, 10402],
    popularity: 50.0,
    original_language: "en",
    tagline: "The road to greatness can take you to the edge.",
  },
  {
    id: 157336,
    title: "Interstellar",
    overview: "Explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    poster_path: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdrop_path: "/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
    release_date: "2014-11-05",
    vote_average: 8.4,
    vote_count: 32000,
    genre_ids: [12, 18, 878],
    popularity: 100.0,
    original_language: "en",
    tagline: "Mankind was born on Earth. It was never meant to die here.",
  },
  {
    id: 496243,
    title: "Parasite",
    overview: "The struggling Kim family sees an opportunity when the son starts tutoring for the wealthy Park family.",
    poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    backdrop_path: "/TU9Bw21MtFI0oIyNlubMVjq36LU.jpg",
    release_date: "2019-05-30",
    vote_average: 8.5,
    vote_count: 16000,
    genre_ids: [35, 53, 18],
    popularity: 70.0,
    original_language: "ko",
    tagline: "Act like you own the place.",
  },
  {
    id: 637,
    title: "Life Is Beautiful",
    overview: "A Jewish father uses humor to protect his son from the horrors of a Nazi concentration camp.",
    poster_path: "/74hLDKjD5aGYOotO6esUVaeISa2.jpg",
    backdrop_path: "/bORe0eI72D874TMawOOFvqWS6Xe.jpg",
    release_date: "1997-12-20",
    vote_average: 8.5,
    vote_count: 12000,
    genre_ids: [35, 18],
    popularity: 45.0,
    original_language: "it",
    tagline: "An unforgettable fable that proves love, family and imagination conquer all.",
  },
  {
    id: 389,
    title: "12 Angry Men",
    overview: "The defense of a delinquent faces formidable odds when one juror forces members to examine the evidence closely.",
    poster_path: "/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg",
    backdrop_path: "/qqHQsStV6exghCM7zbOuYGiLbz7.jpg",
    release_date: "1957-04-10",
    vote_average: 8.5,
    vote_count: 7000,
    genre_ids: [18],
    popularity: 35.0,
    original_language: "en",
    tagline: "Life is in their hands — Death is on their minds!",
  },
  {
    id: 372058,
    title: "Your Name.",
    overview: "Two strangers find themselves linked in a bizarre way and discover they are connected beyond their wildest imagination.",
    poster_path: "/q719jXXEzOoYaps6babgKnONONX.jpg",
    backdrop_path: "/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg",
    release_date: "2016-08-26",
    vote_average: 8.5,
    vote_count: 10000,
    genre_ids: [16, 10749, 18],
    popularity: 55.0,
    original_language: "ja",
    tagline: "Treasuring the experience of a lifetime.",
  },
  {
    id: 19404,
    title: "Dilwale Dulhania Le Jayenge",
    overview: "Raj and Simran meet on a European trip, but their families' cultures refuse to let them be together.",
    poster_path: "/2CAL2433ZeIihfX1Hb2139CX0pW.jpg",
    backdrop_path: "/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg",
    release_date: "1995-10-20",
    vote_average: 8.5,
    vote_count: 4000,
    genre_ids: [35, 18, 10749],
    popularity: 30.0,
    original_language: "hi",
    tagline: "Come Fall In Love.",
  },
];
